services:
  mysql:
    image: mysql:8.0
    container_name: mysql-analytics
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
